name: learn-github-actions
on:
  push:
    branches:
      - main  # Adjust the branch name as needed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Import Secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault-cluster-aws.vault.797ef198-e9b5-4477-b448-5c560fcbe367.aws.hashicorp.cloud:8200
          token: ${{ secrets.VaultToken }}
          namespace: admin
          secrets: |
            kv/data/ci app_secret | APP_SECRET_KEY_ID

      - name: Display Vault Secrets
        run: |
          echo "The secret value is $APP_SECRET_KEY_ID"
