name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
   build:
        # ...
        steps:
            # ...
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                url: https://vault-cluster-aws.vault.797ef198-e9b5-4477-b448-5c560fcbe367.aws.hashicorp.cloud:8200
                token: ${{ secrets.VaultToken }}
                namespace: admin
                secrets: |
                    secret/data/ci/aws_temp accessKey | AWS_ACCESS_KEY_ID ;
                    secret/data/ci/aws_temp secretKey | AWS_SECRET_ACCESS_KEY ;
            # ...
